import pg, { type QueryResultRow } from "pg";

import type {
  AppBlob,
  NewUser,
  OtpKind,
  TenantStore,
  UserPatch,
  UserRecord,
} from "./types.js";

const { Pool } = pg;

// Postgres has no ObjectId equivalent; ids are uuids generated by the database.
// gen_random_uuid() is built in from Postgres 13 onward, which Neon exceeds.
const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS users (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email                 text NOT NULL,
  username              text,
  password_hash         text NOT NULL,
  email_verified        boolean NOT NULL DEFAULT false,
  verify_otp_hash       text,
  verify_otp_expires_at timestamptz,
  reset_otp_hash        text,
  reset_otp_expires_at  timestamptz,
  auth_version          integer NOT NULL DEFAULT 0,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username) WHERE username IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_app_blobs (
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  app_id           text NOT NULL,
  encryption_salt  text NOT NULL,
  blob_iv          text NOT NULL,
  blob_tag         text NOT NULL,
  blob_ciphertext  text NOT NULL,
  blob_version     integer NOT NULL DEFAULT 1,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, app_id)
);

CREATE TABLE IF NOT EXISTS user_app_settings (
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  app_id       text NOT NULL,
  content_root text,
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, app_id)
);
`;

type UserRow = {
  id: string;
  email: string;
  username: string | null;
  password_hash: string;
  email_verified: boolean;
  verify_otp_hash: string | null;
  verify_otp_expires_at: Date | null;
  reset_otp_hash: string | null;
  reset_otp_expires_at: Date | null;
  auth_version: number;
  created_at: Date;
  updated_at: Date;
};

function toUser(row: UserRow | undefined): UserRecord | null {
  if (!row) return null;
  return {
    id: row.id,
    email: row.email,
    username: row.username ?? undefined,
    passwordHash: row.password_hash,
    emailVerified: row.email_verified,
    verifyOtpHash: row.verify_otp_hash ?? undefined,
    verifyOtpExpiresAt: row.verify_otp_expires_at ?? undefined,
    resetOtpHash: row.reset_otp_hash ?? undefined,
    resetOtpExpiresAt: row.reset_otp_expires_at ?? undefined,
    authVersion: row.auth_version,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// Fixed whitelist: patch keys are never interpolated into SQL directly, only mapped
// through this table, and every value is passed as a bound parameter.
const USER_COLUMNS: Record<keyof UserPatch, string> = {
  username: "username",
  passwordHash: "password_hash",
  emailVerified: "email_verified",
  verifyOtpHash: "verify_otp_hash",
  verifyOtpExpiresAt: "verify_otp_expires_at",
  resetOtpHash: "reset_otp_hash",
  resetOtpExpiresAt: "reset_otp_expires_at",
  authVersion: "auth_version",
};

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Ids arrive from a signed token but may be stale or from another driver's format;
// passing a non-uuid to Postgres raises 22P02 instead of returning no rows.
function isValidId(id: string): boolean {
  return UUID_RE.test(id);
}

function needsSsl(uri: string): boolean {
  try {
    const url = new URL(uri);
    if (url.searchParams.get("sslmode") === "disable") return false;
    return !["localhost", "127.0.0.1", "::1"].includes(url.hostname);
  } catch {
    return true;
  }
}

export type PostgresStoreOptions = {
  uri: string;
  connectionTimeoutMillis: number;
  maxPoolSize: number;
};

export async function createPostgresStore(options: PostgresStoreOptions): Promise<TenantStore> {
  const pool = new Pool({
    connectionString: options.uri,
    connectionTimeoutMillis: options.connectionTimeoutMillis,
    // Neon caps concurrent connections and Cloud Run runs many instances, so keep each
    // instance's pool small and let idle sockets drop.
    max: options.maxPoolSize,
    idleTimeoutMillis: 30_000,
    ssl: needsSsl(options.uri) ? { rejectUnauthorized: true } : undefined,
  });

  pool.on("error", (err) => {
    console.error("[auth-service] postgres pool error", err);
  });

  try {
    await pool.query(SCHEMA_SQL);
  } catch (err) {
    await pool.end().catch(() => undefined);
    throw err;
  }

  async function one<T extends QueryResultRow>(sql: string, params: unknown[]): Promise<T | undefined> {
    const result = await pool.query<T>(sql, params);
    return result.rows[0];
  }

  return {
    users: {
      async findById(id) {
        if (!isValidId(id)) return null;
        return toUser(await one<UserRow>("SELECT * FROM users WHERE id = $1", [id]));
      },
      async findByEmail(email) {
        return toUser(await one<UserRow>("SELECT * FROM users WHERE email = $1", [email.toLowerCase()]));
      },
      async findByUsername(username) {
        return toUser(await one<UserRow>("SELECT * FROM users WHERE username = $1", [username]));
      },
      async findByUsernameExcluding(username, exceptUserId) {
        if (!isValidId(exceptUserId)) return null;
        return toUser(
          await one<UserRow>("SELECT * FROM users WHERE username = $1 AND id <> $2", [username, exceptUserId]),
        );
      },
      async findByOtp(kind: OtpKind, email, otpHash, now) {
        const hashCol = kind === "verify" ? "verify_otp_hash" : "reset_otp_hash";
        const expiryCol = kind === "verify" ? "verify_otp_expires_at" : "reset_otp_expires_at";
        return toUser(
          await one<UserRow>(
            `SELECT * FROM users WHERE email = $1 AND ${hashCol} = $2 AND ${expiryCol} > $3`,
            [email.toLowerCase(), otpHash, now],
          ),
        );
      },
      async create(user: NewUser) {
        const row = await one<UserRow>(
          `INSERT INTO users (email, username, password_hash, email_verified, verify_otp_hash, verify_otp_expires_at)
           VALUES ($1, $2, $3, $4, $5, $6)
           RETURNING *`,
          [
            user.email.toLowerCase(),
            user.username ?? null,
            user.passwordHash,
            user.emailVerified,
            user.verifyOtpHash ?? null,
            user.verifyOtpExpiresAt ?? null,
          ],
        );
        return toUser(row)!;
      },
      async update(id, patch) {
        if (!isValidId(id)) return null;

        const assignments: string[] = [];
        const values: unknown[] = [];

        for (const [key, value] of Object.entries(patch)) {
          if (value === undefined) continue;
          const column = USER_COLUMNS[key as keyof UserPatch];
          if (!column) continue;
          values.push(value);
          assignments.push(`${column} = $${values.length}`);
        }

        if (!assignments.length) {
          return toUser(await one<UserRow>("SELECT * FROM users WHERE id = $1", [id]));
        }

        values.push(id);
        return toUser(
          await one<UserRow>(
            `UPDATE users SET ${assignments.join(", ")}, updated_at = now() WHERE id = $${values.length} RETURNING *`,
            values,
          ),
        );
      },
    },

    blobs: {
      async get(userId, appId) {
        if (!isValidId(userId)) return null;
        const row = await one<{
          encryption_salt: string;
          blob_iv: string;
          blob_tag: string;
          blob_ciphertext: string;
          blob_version: number;
          updated_at: Date;
        }>("SELECT * FROM user_app_blobs WHERE user_id = $1 AND app_id = $2", [userId, appId]);

        if (!row) return null;
        return {
          encryptionSalt: row.encryption_salt,
          blobIv: row.blob_iv,
          blobTag: row.blob_tag,
          blobCiphertext: row.blob_ciphertext,
          blobVersion: row.blob_version,
          updatedAt: row.updated_at,
        } satisfies AppBlob;
      },
      async put(userId, appId, blob) {
        await pool.query(
          `INSERT INTO user_app_blobs
             (user_id, app_id, encryption_salt, blob_iv, blob_tag, blob_ciphertext, blob_version, updated_at)
           VALUES ($1, $2, $3, $4, $5, $6, $7, now())
           ON CONFLICT (user_id, app_id) DO UPDATE SET
             encryption_salt = EXCLUDED.encryption_salt,
             blob_iv         = EXCLUDED.blob_iv,
             blob_tag        = EXCLUDED.blob_tag,
             blob_ciphertext = EXCLUDED.blob_ciphertext,
             blob_version    = EXCLUDED.blob_version,
             updated_at      = now()`,
          [userId, appId, blob.encryptionSalt, blob.blobIv, blob.blobTag, blob.blobCiphertext, blob.blobVersion],
        );
      },
    },

    settings: {
      async getContentRoot(userId, appId) {
        if (!isValidId(userId)) return null;
        const row = await one<{ content_root: string | null }>(
          "SELECT content_root FROM user_app_settings WHERE user_id = $1 AND app_id = $2",
          [userId, appId],
        );
        return row?.content_root ?? null;
      },
      async setContentRoot(userId, appId, contentRoot) {
        await pool.query(
          `INSERT INTO user_app_settings (user_id, app_id, content_root, updated_at)
           VALUES ($1, $2, $3, now())
           ON CONFLICT (user_id, app_id) DO UPDATE SET
             content_root = EXCLUDED.content_root,
             updated_at   = now()`,
          [userId, appId, contentRoot],
        );
      },
    },

    // entryStatus is intentionally absent: it is a Spice-only feature and config.ts
    // rejects enabling it on a postgres tenant, so there is no unreachable branch here.

    async close() {
      await pool.end();
    },
  };
}
